name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - run: git fetch --no-tags --prune --depth=5 origin $GITHUB_BASE_REF
      - name: Install project dependencies
        run: npm install
        if: |
          steps.cache-node-modules.outputs.cache-hit != 'true'
      - run: npm affected:lint --fix --base=origin/$GITHUB_BASE_REF
      - run: npm affected:test --base=origin/$GITHUB_BASE_REF
      - run: npm affected:compile --base=origin/$GITHUB_BASE_REF
      - run: npm affected:build --prod --skip-nx-cache --baseHref ${NX_DEPLOY_URL:-/} --deployUrl ${NX_DEPLOY_URL:-/} --base=origin/$GITHUB_BASE_REF --verbose
